name: Generate Maeul in the Sky

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate Maeul in the Sky
        uses: t1seo/maeul-in-the-sky@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and push generated images
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add maeul-in-the-sky-dark.svg maeul-in-the-sky-light.svg
          git commit -m "Aktualizacja mapy kontrybucji [skip ci]" || exit 0
          git push
